### ISSUE TITLE
S1 data download step issue

### ISSUE THREAD

**Issue by KASHKASHOPTIMUS** [kleok/FLOODPY#28]
TypeError: Download_S1_data() got an unexpected keyword argument 'S1_GRD_dir'
![1](https://user-images.githubusercontent.com/107583734/210280108-cc4340ec-9c2a-4bad-84aa-b7ed72fcbe27.png)

**Comment by KASHKASHOPTIMUS** [comment]
THIS IS THE TEMPLATE FILE

**Comment by KASHKASHOPTIMUS** [comment]
[FLOMPYapp_template (copy).txt](https://github.com/kleok/FLOODPY/files/10338905/FLOMPYapp_template.copy.txt)

**Comment by kleok** [comment]
Hello KASHKASHOPTIMUS,
Happy new Year :boom: :boom: :boom:
Thanks for addressing this issue! I updated/added some functionalities and it seems everything runs smoothly now. 
Please pull the changes and have a look at the modified [template file](https://github.com/kleok/FLOODPY/blob/main/FLOODPYapp_template.cfg). Let me know if you managed to resolve this issue.
Best regards,
Kleanthis
