### ISSUE TITLE
Interactive plotting (folium) funcs for notebook

### ISSUE THREAD

**Issue by kleok** [kleok/FLOODPY#35]
- add Layer control in folium
- add more basemaps
- add measure control
- improve colormaps
- Add Sentinel-2 (RGB 432 band combination) as background image
- Add landcover map with legend

**Comment by palexantonakis** [comment]
- add Layer control in folium :heavy_check_mark: (consider to exclude arcgis basemap)
- add more basemaps :heavy_check_mark: (maybe add more CARTO basemaps)
- add measure control :heavy_check_mark: (change its location)
- added draw funcs and export geojson

**Comment by alekfal** [comment]
-    Add Sentinel-2 (RGB 432 band combination) as background image (@alekfal)  :heavy_check_mark:
-    Add landcover map with legend (add legend with LC  @kleok)  :heavy_check_mark:
