### ISSUE TITLE
ValueError: autodetected range of [-inf, inf] is not finite

### ISSUE THREAD

**Issue by acardaras-sanborn** [kleok/FLOODPY#54]
I've modified the configuration file to select my desired date and lat-long:
```
# B1. The datetime of flood event (Format is YYYYMMDDTHHMMSS)
Flood_datetime = 20170910T043000

# C2. AOI BBOX (WGS84)
LONMIN=81.29
LATMIN=24.61
LONMAX=81.46
LATMAX=24.74
```
After running the command `FLOODPYapp.py FLOODPYapp_Pine.cfg --end Floodwater_classification`, I get the following error. The previous steps seem to work fine. Any advice would be greatly appreciated! *Note: I am using WSL (Ubuntu 22.04.1 LTS) and the default cfg file works without any problems.*
```
******************** step - Floodwater_classification ********************
Calculating Bi/multi modality mask...
Calculating global flood mask using global threshold...
Traceback (most recent call last):
  File "/mnt/c/Users/acardaras/Documents/FLOODPY-main/floodpy/FLOODPYapp.py", line 441, in <module>
    main()
  File "/mnt/c/Users/acardaras/Documents/FLOODPY-main/floodpy/FLOODPYapp.py", line 432, in main
    app.run(steps=inps.runSteps, plot=inps.plot)
  File "/mnt/c/Users/acardaras/Documents/FLOODPY-main/floodpy/FLOODPYapp.py", line 400, in run
    self.run_get_flood_map(sname)
  File "/mnt/c/Users/acardaras/Documents/FLOODPY-main/floodpy/FLOODPYapp.py", line 351, in run_get_flood_map
    self.Flood_local_map_RG_morph,] = Calc_flood_map(Preprocessing_dir = self.Preprocessing_dir,
  File "/home/acardaras/.local/lib/python3.10/site-packages/floodpy/Floodwater_classification/Classification.py", line 97, in Calc_flood_map
    glob_thresh = threshold_Otsu(t_scores_flatten)
  File "/home/acardaras/.local/lib/python3.10/site-packages/floodpy/Floodwater_classification/Thresholding_methods.py", line 51, in threshold_Otsu
    return threshold_otsu(data.flatten())
  File "/home/acardaras/.local/lib/python3.10/site-packages/skimage/filters/thresholding.py", line 364, in threshold_otsu
    counts, bin_centers = _validate_image_histogram(image, hist, nbins)
  File "/home/acardaras/.local/lib/python3.10/site-packages/skimage/filters/thresholding.py", line 306, in _validate_image_histogram
    counts, bin_centers = histogram(
  File "/home/acardaras/.local/lib/python3.10/site-packages/skimage/_shared/utils.py", line 394, in fixed_func
    return func(*args, **kwargs)
  File "/home/acardaras/.local/lib/python3.10/site-packages/skimage/exposure/exposure.py", line 266, in histogram
    hist, bin_centers = _histogram(image, nbins, source_range, normalize)
  File "/home/acardaras/.local/lib/python3.10/site-packages/skimage/exposure/exposure.py", line 300, in _histogram
    hist, bin_edges = np.histogram(image, bins=bins, range=hist_range)
  File "<__array_function__ internals>", line 5, in histogram
  File "/usr/lib/python3/dist-packages/numpy/lib/histograms.py", line 793, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/usr/lib/python3/dist-packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/usr/lib/python3/dist-packages/numpy/lib/histograms.py", line 323, in _get_outer_edges
    raise ValueError(
ValueError: autodetected range of [-inf, inf] is not finite
```

**Comment by acardaras-sanborn** [comment]
Increasing the number of "before_flood_days" in the configuration file fixed this issue.

**Comment by kleok** [comment]
Hello @acardaras-sanborn,
It turns out that the particular issue was due to the small number of pre-flood images (only one) based on your configuration. Me and @alekfal tested that Floodpy runs succesfully when you change to ```before_flood_days``` parameter to ```40```.
``` 
# B2. Days before flood event for baseline stack construction
before_flood_days = 40
```
However, we saw that based on your configuration at that specific ```Flood_datetime``` and given AOI borders, no significant decrease on Sentinel-1 backscatter can be observed. We suggest to have a look at the created ```png``` files at your ```projectfolder```. We hope that this helps :smile: 
Let us know if you need any more clarifications
Best regards

**Comment by acardaras-sanborn** [comment]
Thank you @kleok. Should the Flood_datetime be given in UTC or a different format?

**Comment by kleok** [comment]
UTC format is fine.

**Comment by acardaras-sanborn** [comment]
Could you give some insight as to why the baseline_images.png shows a low ERA5_tp_mm during the expected flood event? There was a flood at the AOI on 2017-09-10.
![baseline_images](https://user-images.githubusercontent.com/112427170/219126166-d4d63eb9-144b-4d69-aa84-41b09cb45e5e.png)

**Comment by kleok** [comment]
Hello @acardaras-sanborn, it seems that according to ERA5 precipitation data and based on Sentinel-1 backscatter no major flood event occurred. According to my personal experience I want to highlight these:
- ERA5 reanalysis product includes precipitation with high accuracy. For more information you can have a look [here](https://www.ecmwf.int/en/forecasts/datasets/reanalysis-datasets/era5). For your case, I suggest to have a look at local meteorological data from other sources to better understand the spatiotemporal distrubution of the precipitation.
- Sentinel-1 backscatter provides an invaluable data source for flood mapping/monitoring but should not be taken as granted that is going to work for every flood event. I suggest to try a more sophisticated approach using Sentinel-1 data [here](https://www.mdpi.com/2072-4292/11/2/107) and/or have a look at other data sources.

I hope this helps you :smile:

**Comment by acardaras-sanborn** [comment]
Thank you for your ongoing help and advice. I have changed my AOI and am positive flooding has occurred at the provided date-time. I would like to verify that the attached t-score and flood map images make sense to you. I've also attached an image with the flood map overlayed on the t-score image. It seems that the boundaries of the flood map are slightly eroded. 

```
# B1. The datetime of flood event (Format is YYYYMMDDTHHMMSS)
Flood_datetime = 20200916T050000

# B2. Days before flood event for baseline stack construction
before_flood_days = 40

# C2. AOI BBOX (WGS84)
LONMIN=87.13
LATMIN=30.29
LONMAX=87.43
LATMAX=30.52
```

![t_scores_VV_VH_db](https://user-images.githubusercontent.com/112427170/219766363-430fd537-cad5-4c91-b165-d6a1994ec105.png)
![Flood_map_Sally](https://user-images.githubusercontent.com/112427170/219766368-8c2d2e8f-334c-48a2-9bc8-0f7c97485a9d.png)
![sally_overlay](https://user-images.githubusercontent.com/112427170/219766370-ac7f2dc9-d226-41c5-b9d5-50b5523d5d64.png)
