### ISSUE TITLE
Subset AOI pre-processing step error

### ISSUE THREAD

**Issue by KASHKASHOPTIMUS** [kleok/FLOODPY#58]
The error occurs during the pre-processing step, the project template file and error image are attached 
![WhatsApp Image 2023-03-05 at 12 28 14 AM](https://user-images.githubusercontent.com/107583734/222945440-6e8c0dfc-99af-46d9-9ad9-5c6e68ce6125.jpeg)
[FLOODPYapp_template.txt](https://github.com/kleok/FLOODPY/files/10890926/FLOODPYapp_template.txt)

**Comment by KASHKASHOPTIMUS** [comment]
Also the project template file is attached

**Comment by kleok** [comment]
Hello @KASHKASHOPTIMUS, unfortunately I want not able to reproduce your error :thinking: . However, I commited and relevant change based on my interpretation of the attached error.   
I managed to run FloodPy successfully when I changed the ```before_flood_days = 20```  to ```before_flood_days = 60```.  
Let me know if this also works for you :smile:
