### ISSUE TITLE
AttributeError: 'FloodwaterEstimation' object has no attribute 'precipitation_df'?

### ISSUE THREAD

**Issue by minaahmed** [kleok/FLOODPY#63]
Hello, please advise how to solve this error 

![errorm](https://user-images.githubusercontent.com/45327396/226559498-8e6ee8f3-7661-43dd-a499-6474ae7f1359.png)

**Comment by kleok** [comment]
Hello @minaahmed :smiley: 
Thanks for using Floodpy! The following error is caused due to a recent change of the software functionalities. In order to overcome this issue for now you can run all the steps (**without** using the ```--dostep``` option) with the following command:
```FLOODPYapp.py FLOODPYapp_template.cfg ```

We will have a closer look at this issue  and commit the relevant changes for the ```--dostep``` option.
Let us know if this works for you :blush:

**Comment by minaahmed** [comment]
@kleok Thanks a lot, it works but I got other error when I am using the code for other study area??
![floodpyerrormessage](https://user-images.githubusercontent.com/45327396/227149233-560ccb6d-76c5-4d33-865a-1a26097cef78.png)

**Comment by kleok** [comment]
Hello @minaahmed, please provide your configuration file in order to have a better look at your issue.
Thanks a lot :smile:

**Comment by kleok** [comment]
Hello @minaahmed,
I commited some modifications and I think now you will be able to perform your analysis. Regarding your question about the cumulative precipitation threshold value which is referred as ```accumulated_precipitation_threshold``` in the configuration file, it is used to drop pre-flood images that represent high soil moisture conditions. The value of ```accumulated_precipitation_threshold``` should be decided by the operator and depends on the area of interest. In your case, it is clear all the images before the big rain **can** be used for pre-flood stack generation.
![image](https://user-images.githubusercontent.com/7121726/232240720-f17acbfb-444a-4e78-9426-51af7dff8b42.png)
I hope this helps :smile: 
Let me know if you need anything further :slightly_smiling_face:

**Comment by minaahmed** [comment]
Hello
Kindly could you share the configuration file u used for below anaylsis


Sent from Yahoo Mail for iPhone


On Saturday, April 15, 2023, 9:09 PM, Kleanthis Karamvasis ***@***.***> wrote:




Hello @minaahmed,
I commited some modifications and I think now you will be able to perform your analysis. Regarding your question about the cumulative precipitation threshold value which is referred as accumulated_precipitation_threshold in the configuration file, it is used to drop pre-flood images that represent high soil moisture conditions. The value of accumulated_precipitation_threshold should be decided by the operator and depends on the area of interest. In your case, it is clear all the images before the big rain can be used for pre-flood stack generation.

I hope this helps 😄
Let me know if you need anything further 🙂

**Comment by minaahmed** [comment]
Hello I was trying to detect flooded area for location and information below but flood is very little area, can you support me on solving this issue 

LONMIN=56.227
LATMIN=24.981
LONMAX=56.372 
LATMAX=25.125
accumulated_precipitation_threshold =20

#Flood_datetime = '20220728T091800'#20220727T091800'
Flood_datetime = '20220728T142509'

# B2. Days before flood event for baseline stack construction
before_flood_days = 90 ### 

# B3. Days after flood event
after_flood_days = 4
Hope to hear from you as soon as possible 
Sent from Yahoo Mail for iPhone


On Saturday, April 15, 2023, 9:09 PM, Kleanthis Karamvasis ***@***.***> wrote:




Hello @minaahmed,
I commited some modifications and I think now you will be able to perform your analysis. Regarding your question about the cumulative precipitation threshold value which is referred as accumulated_precipitation_threshold in the configuration file, it is used to drop pre-flood images that represent high soil moisture conditions. The value of accumulated_precipitation_threshold should be decided by the operator and depends on the area of interest. In your case, it is clear all the images before the big rain can be used for pre-flood stack generation.

I hope this helps 😄
Let me know if you need anything further 🙂
