### ISSUE TITLE
Floodpy beginposition error

### ISSUE THREAD

**Issue by Donna-syc** [kleok/FLOODPY#70]
Hello, I am a third year bachelor's student in Geographic Information System and I am using FLOODPY to do a flood mapping study in my area. I have encountered the following error several times. Please help me on how I can resolve this. Also I don't understand the days_back part. Would you be so kind as to give me a short explanation because in the documentation its not so clear.  Below is the error message. Thank you.

![error (1)](https://github.com/kleok/FLOODPY/assets/74425367/41a15275-067e-4609-9b97-153ddecf3a91)

**Comment by kleok** [comment]
Hello @Donna-syc 
Thanks for using Floodpy :smile: Could you please share with me the configuration file? This will help a lot to better understand your issue.
```days_back``` is a parameter related to the identification of "wet" Sentinel-1 acquisitions. "Wet" acquisitions will not be used for the pre-flood stack creation. ```days_back``` expresses how many days we will have to go back to calculate the accumulated precipitation for each Sentinel-1 acquisition. For example, if ```days_back = 7``` and we have a Sentinel-1 acquisition acquired at ```08 February 2023``` we will add the precipitation of all the ```7 days``` before ```08 February 2023```. This calculated accumulated precipitation value is then compared with ```accumulated_precipitation_threshold``` and we then decide if the Sentinel-1 acquisition is going to be used for pre-flood stack creation.
I hope my explanation helps you :smiley:

**Comment by Donna-syc** [comment]
Hey, I hope this email finds you well. Thank you so much for the
explanation I understand better now. Below is my configuration file.

Thank you.

**Comment by Donna-syc** [comment]
Good day sir,

I realized that I got that error because my coordinates had been written
wrongly and once I fixed it. I got an output.  However, the flood image
that I got I can't properly comprehend because it looks different from the
examples in your report. I will send it to you to get your output because
maybe I did something wrong.

Kind regards,

Tuyeimo
