### ISSUE TITLE
Creating orbit geometries from the era of 2 Sentinel-1 (A anf B) creates Multypoligons

### ISSUE THREAD

**Issue by mazingaro** [kleok/FLOODPY#76]
In FlooDPYapppy:

`self.query_S1_df['geometry'] = self.query_S1_df.GeoFootprint.apply(create_polygon)`

calls create_polygon() from geo_utils.py:
```
from shapely.geometry import Polygon

def create_polygon(coordinates):
    return Polygon(coordinates['coordinates'][0])
```

This one produces a Multipolygon for Sentinel-1 before 2022 (cca.). 

Such geometry raises this  error
`ValueError: A LinearRing must have at least 3 coordinate tuples`
 after calling:
`Floodpy_app.sel_S1_data(sel_flood_date)`

You can try to reproduce the error with this parameters:

```
pre_flood_start = '20191019T000000'
pre_flood_end = '20191027T000000'
flood_start = '20191115T000000'
flood_end = '20191118T00000'

# AOI BBOX (WGS84)
LONMIN = 12.42
LATMIN = 45.43
LONMAX = 13.11
LATMAX = 45.86

```

**Comment by kleok** [comment]
Hello @mazingaro 
Thank a lot for using Floodpy :smile: 
I commited some improvements and I think that  this issue has been resolved. Could you please verify that?
Thanks in advance!

**Comment by mazingaro** [comment]
@kleok 
I've checked the new version and it's already stuck on the ERA5 plot with:

`Floodpy_app.plot_ERA5_precipitation_data()`

outputing

`TypeError: datetime64 type does not support sum operations`

If I ignore plotting and continue,

`Floodpy_app.query_S1_data()`
`print('The available dates for flood mapping are: \n --> {}'.format('\n --> '.join(map(str, Floodpy_app.flood_candidate_dates))))`

outputs 
`TypeError: Cannot compare tz-naive and tz-aware datetime-like objects`

It would be appropriate to put both the errosrs in new issues, but for now it's maybe easier for you to read them here.

**Comment by kleok** [comment]
Hello @mazingaro,
At first, let's focus on the `TypeError: datetime64 type does not support sum operations`. 
I believe this error is related to the provided format of the temporal information.
Are you running the provided example notebook without any changes?
Could you please verify that in the notebook section 2. Set input parameters for FLOODPY your inputs have the same format? 

```
# The start and end datetimes for Pre-flood time span and flood time span (Format is YYYYMMDDTHHMMSS in UTC)
pre_flood_start = '20230701T030000'
pre_flood_end = '20230903T030000'
flood_start = '20230903T030000'
flood_end = '20230909T030000'
```
Looking forward for you answer :blush:

**Comment by mazingaro** [comment]
Yes. If I run the original notebook with this 

`# The start and end datetimes for Pre-flood time span and flood time span (Format is YYYYMMDDTHHMMSS in UTC)`
`pre_flood_start = '20230701T030000'`
`pre_flood_end = '20230903T030000'`
flood_start = '20230903T030000'
`flood_end = '20230909T030000'`

and this change

`# AOI BBOX (WGS84)`
`LONMIN = 12.42`
`LATMIN = 45.43`
`LONMAX = 13.11`
`LATMAX = 45.86`

I get through the plotting and get the error I've reported before:

`Floodpy_app.query_S1_data()`
`print('The available dates for flood mapping are: \n --> {}'.format('\n --> '.join(map(str, Floodpy_app.flood_candidate_dates))))`

outputs
`TypeError: Cannot compare tz-naive and tz-aware datetime-like objects`

The plot works, before I messed up something.

These are the error locations:
`/FLOODPY/floodpy/FLOODPYapp.py:138, in FloodwaterEstimation.query_S1_data(self)`
`    137 def query_S1_data(self):`
`--> 138     self.query_S1_df, self.flood_candidate_dates = query_Sentinel_1(self)`

`/FLOODPY/floodpy/Download/Query_Sentinel_1_products.py:53, in query_Sentinel_1(Floodpy_app)`
`     50 query_df.index = pd.to_datetime(query_df['beginningDateTime'])`
`     51 query_df = query_df.drop_duplicates('beginningDateTime').sort_index()`
`---> 53 flood_candidate_dates = query_df['relativeOrbitNumber']`
```
[Floodpy_app.flood_datetime_start:Floodpy_app.flood_datetime_end].index.values
     54 return query_df, flood_candidate_dates

```

**Comment by kleok** [comment]
I used the following configuration, and I was able to run floodpy without any issues.
```
# The start and end datetimes for Pre-flood time span and flood time span (Format is YYYYMMDDTHHMMSS in UTC)
pre_flood_start = '20230701T030000'
pre_flood_end = '20230903T030000'
flood_start = '20230903T030000'
flood_end = '20230909T030000'

# AOI BBOX (WGS84)
LONMIN = 12.42
LATMIN = 45.43
LONMAX = 13.11
LATMAX = 45.86
```
For clarity purposes please answer the following questions:
- Do you still encounter the `TypeError: datetime64 type does not support sum operations` from `Floodpy_app.plot_ERA5_precipitation_data()`? If not, is your ERA5 plot looking like the following?
![image](https://github.com/user-attachments/assets/464a51fd-5b51-4266-9a0a-ebba7f8673fd)

- Do you ignore the aforementioned error and run the `Floodpy_app.query_S1_data()` where you encounter the` TypeError: Cannot compare tz-naive and tz-aware datetime-like objects`? If you are not able to generate this figure please don`t proceed and check your `.cdsapirc` file under your `HOME` based on installation notes 1.3 Account setup for downloading global atmospheric model data

**Comment by mazingaro** [comment]
@kleok

> Do you still encounter the TypeError: datetime64 type does not support sum operations from Floodpy_app.plot_ERA5_precipitation_data()? If not, is your ERA5 plot looking like the following?

No, I don't. The plot works fine, as mentuioned i messed something up there :)

> Do you ignore the aforementioned error and run the Floodpy_app.query_S1_data() where you encounter the TypeError: Cannot compare tz-naive and tz-aware datetime-like objects? If you are not able to generate this figure please don't proceed and check your .cdsapirc file under your HOME based on installation notes 1.3 Account setup for downloading global atmospheric model data

The  .cdsapirc file is under home and the download is working. 

> I get through the plotting and get the error I've reported before:
> 
> Floodpy_app.query_S1_data()
> print('The available dates for flood mapping are: \n --> {}'.format('\n --> '.join(map(str, Floodpy_app.flood_candidate_dates))))
> 
> outputs
> TypeError: Cannot compare tz-naive and tz-aware datetime-like objects
