### ISSUE TITLE
requirements update

### ISSUE THREAD

**Issue by mazingaro** [kleok/FLOODPY#79]
The requirements.txt doesn't contain pytorch, torchvision and other new dependencies.

**Comment by kleok** [comment]
This is true! We will try to update the requirements.txt file with the all the required libraries. For now I suggest you to create a conda environment by using FLOODPY_gpu_env.yml

https://github.com/kleok/FLOODPY/blob/0c986d9af419d8e0e7dc9c926ff339c16ef6f2f8/FLOODPY_gpu_env.yml#L1
